# Generated by Django 5.2.8 on 2026-06-24 13:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='wrench', help_text="Identifiant de l'icône SVG", max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('client', 'Client'), ('technicien', 'Technicien'), ('admin', 'Administrateur')], default='client', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('city', models.CharField(blank=True, default='Bamako', max_length=80, verbose_name='Ville')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Compte suspendu')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('default_lat', models.FloatField(blank=True, null=True)),
                ('default_lng', models.FloatField(blank=True, null=True)),
                ('installation_note', models.CharField(blank=True, max_length=200, verbose_name="Type d'installation")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Présentation')),
                ('zones', models.CharField(blank=True, max_length=200, verbose_name="Zones d'intervention")),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('verification', models.CharField(choices=[('pending', 'En attente de validation'), ('verified', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=12)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('busy', 'En intervention'), ('offline', 'Hors ligne')], default='offline', max_length=12)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('rating_avg', models.FloatField(default=0, verbose_name='Note moyenne')),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('completed_missions', models.PositiveIntegerField(default=0, verbose_name='Missions terminées')),
                ('hourly_indication', models.PositiveIntegerField(default=5000, verbose_name='Indication FCFA / heure')),
                ('skills', models.ManyToManyField(blank=True, related_name='technicians', to='accounts.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating_avg', '-completed_missions'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('id', "Pièce d'identité"), ('cert', 'Certification / diplôme'), ('other', 'Autre justificatif')], default='id', max_length=10)),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.technicianprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
